### PR TITLE
Clarify example requirements

### PR DESCRIPTION
**Pull request by gummif**
See issue #332

### CODE REVIEW

**Comment by sigiesec** [comment]
Hm, I don't think it is a good idea to add this. The README file is part of the repository, so it is implicitly clear that it refers to the current repository state. This may be wrong, but in that case it is clear it must be fixed. Adding a reference to a particular version only adds another potential place which may go out of sync. In particular, when you modify the example in the future, you would need to check which older version it is still working with.

**Comment by gummif** [comment]
Good point. How about only specifying that the example requires C++11, since 98 is still technically supported?

**Comment by sigiesec** [comment]
Yes, specifying that it requires C++11 is a good idea!

**Comment by gummif** [comment]
Well I just realized that since it uses string_view it actually requires C++17...

**Comment by gummif** [comment]
This PR ready now, using str_buffer instead of string_view.

**Comment by sigiesec** [comment]
Great, thanks!

**Pull request merged**
