### PR TITLE
Fixes warning noexcept

### PR DESCRIPTION
**Pull request by Teebonne**
This type of function should not throw, adding noexcept

### CODE REVIEW

**Comment by gummif** [comment]
You must use the ZMQ_NOTHROW macro instead of noexcept for compatibility.

**Comment by Teebonne** [comment]
Not sure this would fix the problem, or maybe I didn't understand what you mean with this macro.
A move operator should never throw exceptions (see [C++ Core Guidelines C.66](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-move-noexcept))

**Comment by Teebonne** [comment]
Done, thanks!

**Comment by gummif** [comment]
Thanks

**Pull request merged**
