### PR TITLE
Move header files to an include directory

### PR DESCRIPTION
**Pull request by gummif**
It is standard practice to have exported headers in a directory called `include`. I would have liked to move the code to `include/cppzmq` but that would be a breaking change forcing code to do `#include <cppzmq/zmq.hpp>` (maybe for the next major release?).

### CODE REVIEW

**Comment by bluca** [comment]
please don't, this will break a lot of scripts and packages

**Comment by gummif** [comment]
@bluca Yes it will for non-cmake consumers. Would it make you more comfortable if this change were made in a major release (v5.0)?

**Comment by bluca** [comment]
Sorry, but I don't feel like a cosmetic change on the repository layout is a good enough reason to break compatibility for all distros, regardless of versioning

**Comment by sigiesec** [comment]
While I don't particularly like the current layout either, I agree with @bluca here. We only have two header files, so the situation on our side is not bad enough to warrant all the troubles a layout change might cause.

**Comment by gummif** [comment]
I understand the concerns and this PR can be closed. Although I disagree that code layout change are unacceptable at the same time breaking code changes are introduced with a major version. I guess that's a conflict between long term backwards compatibility and using new features and best practices.

**Comment by bluca** [comment]
Breaking backward compatibility can happen and the process is defined in C4 - but given the huge inconvenience, it should balanced by a very compelling requirement

**Pull request closed without merging**
