### PR TITLE
Problem: coverate not supported

### PR DESCRIPTION
**Pull request by kurdybacha**
Solution: enable code coverage and report it to codecov.io
Note: This requires zeromq/cppzmq to be enabled on codecov.io

### CODE REVIEW

**Comment by bluca** [comment]
Why the change from coveralls?

**Comment by kurdybacha** [comment]
just found it easier to integrate and easier to work with (subjective). If that is an issue I can go back to coverall, no problem.

**Comment by bluca** [comment]
Just curious on the pro and cons,I don't really mind or way or the other

**Comment by kurdybacha** [comment]
I will make coveralls work on a separate branch and we can compare and make more informative decision

**Comment by kurdybacha** [comment]
@bluca just created another PR with `coveralls`. Both `coveralls` and `codecov` show same results now.
With codecov there is some more work required as it should not show `tests`.
Overall both are good. I don't have strong opinion so whatever you merges is fine with me.
I found codecov integration easier (no need for pip install, simpler usage) and UI seems more readable (e.g. similar fonts as on github) but as `libzmq` uses `coveralls` maybe we can keep it consistent.

**Pull request closed without merging**
