### PR TITLE
Add some initial tests, add some build/version CI variants

### PR DESCRIPTION
**Pull request by sigiesec**

### CODE REVIEW

**Comment by bluca** [comment]
@sigiesec could you please rebase and remove tests/example_add.o ? otherwise it will stay in the repo forever as it's a binary file

**Comment by bluca** [comment]
Also why don't we get the coveralls messages on the libzmq repo? I'm pretty sure I set that up, and we used to at some point

**Comment by sigiesec** [comment]
@bluca Oops, good you noticed that. The object file should be gone now.

I don't know why the coverage report isn't working. I also think I remember that it worked in libzmq some time ago. On the other hand, I don't know why it works here. I did nothing special to get it comment here. Probably it is some kind of permission problem? (However, the coverage isn't correct. It shows lines as non-executed, which must definitely have been executed, and some others are completely missing. I don't know why, but I fear I cannot analyze this deeply soon)

**Comment by sigiesec** [comment]
@bluca Could you also give me permissions on cppzmq such that I can edit the issue labels?

**Comment by bluca** [comment]
you should have the invitation

**Comment by sigiesec** [comment]
@bluca Yes, thanks a lot :)

**Comment by bluca** [comment]
no problem, thanks for taking care of this repository, it desperately needed some attention

**Pull request merged**
