### PR TITLE
Problem: Appveyor build is slow.

### PR DESCRIPTION
**Pull request by kurdybacha**
Solution: use Appveyor caching for libzmq dependency

@bluca @sigiesec this is from appveyor website:

> Note: By default, saving cache is disabled in Pull Request builds. Use Save build cache in Pull Requests checkbox on the General tab of project settings if you need to save cache during PR builds. This setting is not exposed in YAML to prevent unauthorized cache modifications.

### CODE REVIEW

**Comment by bluca** [comment]
It doesn't seem to be making a difference? Can't see anything in the logs

**Comment by kurdybacha** [comment]
If you have just enabled it maybe it will apply on next pull request? I am just guessing here as I can not find anything useful in the appveyor docs.

**Comment by bluca** [comment]
It seems to kick in after a rebuild but it fails:

```
Cache 'libzmq-4.2.5' - Restored
Running Install scripts
if not exist libzmq-%ZMQ_VERSION% ( appveyor DownloadFile https://github.com/zeromq/libzmq/archive/v%ZMQ_VERSION%.zip && 7z x v%ZMQ_VERSION%.zip >NUL && cmake -H./libzmq-%ZMQ_VERSION% -BBuild-libzmq -DENABLE_DRAFTS=ON -DWITH_PERF_TOOL=OFF -DZMQ_BUILD_TESTS=OFF -DENABLE_CPACK=OFF -A%PLATFORM% && cmake --build Build-libzmq && cmake -H. -BBuild -DCMAKE_PREFIX_PATH=./Build-libzmq -A%PLATFORM% )
Specified build project file or folder does not exist: "Build/cppzmq.sln"
```

**Comment by bluca** [comment]
It fails later now:

```
Build FAILED.
"C:\projects\cppzmq\Build\cppzmq.sln" (default target) (1) ->
"C:\projects\cppzmq\Build\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"C:\projects\cppzmq\Build\tests\unit_tests.vcxproj.metaproj" (default target) (12) ->
"C:\projects\cppzmq\Build\tests\unit_tests.vcxproj" (default target) (13) ->
(ClCompile target) -> 
  c:\projects\cppzmq\zmq.hpp(51): fatal error C1083: Cannot open include file: 'zmq.h': No such file or directory [C:\projects\cppzmq\Build\tests\unit_tests.vcxproj]
  c:\projects\cppzmq\zmq.hpp(51): fatal error C1083: Cannot open include file: 'zmq.h': No such file or directory [C:\projects\cppzmq\Build\tests\unit_tests.vcxproj]
  c:\projects\cppzmq\zmq.hpp(51): fatal error C1083: Cannot open include file: 'zmq.h': No such file or directory [C:\projects\cppzmq\Build\tests\unit_tests.vcxproj]
  c:\projects\cppzmq\zmq.hpp(51): fatal error C1083: Cannot open include file: 'zmq.h': No such file or directory [C:\projects\cppzmq\Build\tests\unit_tests.vcxproj]
    0 Warning(s)
    4 Error(s)
Time Elapsed 00:00:24.11
```

**Comment by kurdybacha** [comment]
Yes, I saw this on my branch already. I will investigate in the evening and let you know when fixed. sorry for this noise but it is pain to test this. Maybe I should cancel this pull request until it is fixed?

**Comment by bluca** [comment]
I don't mind, up to you

**Comment by kurdybacha** [comment]
@bluca it should be fine now. After rebuild you should see more x2 speedup now. Still room to improve...

**Comment by bluca** [comment]
much better, thanks

**Pull request merged**
