### PR TITLE
Problem: addition of new single-argument message_t introduces ambigui…

### PR DESCRIPTION
**Pull request by sigiesec**
…ty when calling e.g. socket_t::send

Solution: make single-argument constructor explicit

### CODE REVIEW

**Comment by sigiesec** [comment]
@bluca can you give this a short look and merge it if you see no issues?

**Comment by kurdybacha** [comment]
Hi Simon,

thanks for looking at this. Could you explain ambiguity that you experience?
I am not sure if `explicit` specifier with templates arguments helps here..

**Comment by sigiesec** [comment]
It does. I tested it with our old code. You can have a look at the new test case that I added, which is something that worked before. When you remove the explicit again, you will get an ambiguous function call error.

**Comment by kurdybacha** [comment]
Got it. `inline bool recv(message_t *msg_, int flags_ = 0)` is called in this case. Thanks.

**Pull request merged**
