### PR TITLE
Problem: Socket options lack type-safety 

### PR DESCRIPTION
**Pull request by gummif**
Solution: Implement a type for each socket option.

Each option has an associated type, therefore they
can't be simply defined as an enum class.

That's a lot of options! I think this is one of the last places that are truly dangerous in the current API, where e.g. `s.setsockopt(ZMQ_ROUTING_ID, std::string("foo"));` will not do what you expect.

### CODE REVIEW

**Comment by gummif** [comment]
Yes, this is a bit of a burden but worth it I think since the package advertises type safety.
There is one benefit to this design that the user could define new or old deprecated options simply as `using old_opt = zmq::sockopt::integral_option<ZMQ_OLD_OPT, int>;` and use that to set and get options.

I think I could add the tests, shouldn't be a lot of trouble.

I did not clang format, I will do that.

**Comment by sigiesec** [comment]
> Yes, this is a bit of a burden but worth it I think since the package advertises type safety.

Yes, you're right. It matches the design goals, and while it is an additional maintenance burden, it's worth it :)

> There is one benefit to this design that the user could define new or old deprecated options simply as `using old_opt = zmq::sockopt::integral_option<ZMQ_OLD_OPT, int>;` and use that to set and get options.

Yes, that's great!

> I think I could add the tests, shouldn't be a lot of trouble.

Ok, fine then :)

> I did not clang format, I will do that.

:)

**Comment by gummif** [comment]
I was unable to test the bindtodevice and gssapi options. I also found a bug in libzmq documentation (https://github.com/zeromq/libzmq/pull/3851).

**Comment by sigiesec** [comment]
Great, thanks a lot for doing this! I think missing the bindtodevice and gssapi options is acceptable :)

**Pull request merged**
