### PR TITLE
Fixed build by adding FindZeroMQ.cmake and modifying CMakeLists.txt

### LINKED ISSUE #127: Missing FindZeroMQ.cmake
Attempting to build on Ubuntu 16.04 after installing ZeroMQ 4.2.1

> CMake Error at CMakeLists.txt:4 (find_package):
>   By not providing "FindZeroMQ.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "ZeroMQ", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "ZeroMQ" with any
>   of the following names:
> 
>     ZeroMQConfig.cmake
>     zeromq-config.cmake
> 
>   Add the installation prefix of "ZeroMQ" to CMAKE_PREFIX_PATH or set
>   "ZeroMQ_DIR" to a directory containing one of the above files.  If "ZeroMQ"
>   provides a separate development package or SDK, be sure it has been
>   installed.

> -- Configuring incomplete, errors occurred!

Am i invoking cmake incorrectly?

### PR DESCRIPTION
**Pull request by stevemk14ebr**
Fixes #127

### CODE REVIEW

**Comment by bluca** [comment]
I don't think the FindZeroMQ.cmake is needed anymore since this PR was merged: https://github.com/zeromq/libzmq/pull/2295

**Comment by JohanMabille** [comment]
Indeed `ZeroMQConfig.cmake` should be generated when ZeroMQ is installed with cmake, and then ZeroMQ can be find with `find_package`.

**Comment by stevemk14ebr** [comment]
I've tried building ZeroMQ 5 or so different times, including on VM's to verify i wasn't insane. If it's supposed to generate that .cmake file then it fails to do so.

**Comment by bluca** [comment]
That's not cmake, it's autotools, build libzmq with cmake too

**Comment by stevemk14ebr** [comment]
Why do two seperate build tools need to be invoked, and why is only one of them documented:

Official docs to build as quoted from the INSTALL file in repo
> The simplest way to compile this package is:
> 
>   1. `cd' to the directory containing the package's source code and type
>      `./configure' to configure the package for your system.
> 
>      Running `configure' might take a while.  While running, it prints
>      some messages telling which features it is checking for.
> 
>   2. Type `make' to compile the package.
> 
>   3. Optionally, type `make check' to run any self-tests that come with
>      the package. Note that `make -j check' is not supported as some
>      tests share infrastructure and cannot be run in parallel.
> 
>   4. Type `make install' to install the programs and any data files and
>      documentation.

**Comment by stevemk14ebr** [comment]
Ok so i tried building with libzmq with cmake too and the file is still not generated, here's what i did. 

Clone libzmq and unzip, cd to dir
mkdir build
cd build
cmake ../
make
sudo make install

clone cppzmq, unzip, cd to dir
mkdir build
cmake ../
*failed to find FindZeroMq.cmake*

please try building this repo, unless im mistaken the build process is broken.

**Comment by bluca** [comment]
Works just fine:

```
$ cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/test
-- Using tweetnacl for CURVE security
-- Detected epoll polling method
-- Detected ZMQ Version - 4.2.3
-- Checking whether EFD_CLOEXEC is supported
-- Checking whether SOCK_CLOEXEC is supported
-- Checking whether SO_KEEPALIVE is supported
-- Checking whether TCP_KEEPCNT is supported
-- Checking whether TCP_KEEPIDLE is supported
-- Checking whether TCP_KEEPINTVL is supported
-- Checking whether TCP_KEEPALIVE is supported
-- Checking whether TIPC is supported
-- Checking pthread_setname signature
CMake Warning (dev) at tests/CMakeLists.txt:179 (message):
  Test 'test_hwm_max' is not known to CTest.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at tests/CMakeLists.txt:179 (message):
  Test 'test_security_gssapi' is not known to CTest.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/luca/git/libzmq/build
$ make -j5 install
[ 31%] Built target libzmq-static
[ 63%] Built target libzmq
[ 63%] Built target remote_thr
[ 63%] Built target local_lat
[ 63%] Built target remote_lat
[ 64%] Built target local_thr
[ 64%] Built target inproc_lat
[ 64%] Built target inproc_thr
[ 64%] Built target test_udp
[ 65%] Built target test_use_fd_tcp
[ 66%] Built target test_poller
[ 67%] Built target test_router_mandatory_hwm
[ 67%] Built target test_filter_ipc
[ 67%] Built target test_thread_safe
[ 67%] Built target test_pair_ipc
[ 68%] Built target test_proxy
[ 68%] Built target test_monitor
[ 68%] Built target test_bind_after_connect_tcp
[ 69%] Built target test_timers
[ 69%] Built target test_xpub_welcome_msg
[ 69%] Built target test_base85
[ 70%] Built target test_abstract_ipc
[ 70%] Built target test_stream_timeout
[ 70%] Built target test_ipc_wildcard
[ 70%] Built target test_router_handover
[ 70%] Built target test_metadata
[ 70%] Built target test_srcfd
[ 71%] Built target test_bind_src_address
[ 71%] Built target test_getsockopt_memset
[ 71%] Built target test_capabilities
[ 71%] Built target test_heartbeats
[ 72%] Built target test_atomics
[ 72%] Built target test_dgram
[ 73%] Built target test_pub_invert_matching
[ 74%] Built target test_sockopt_hwm
[ 74%] Built target test_xpub_manual
[ 75%] Built target test_xpub_nodrop
[ 75%] Built target test_security_plain
[ 75%] Built target test_stream_exceeds_buffer
[ 75%] Built target test_ancillaries
[ 76%] Built target test_stream_empty
[ 76%] Built target test_pair_tcp
[ 76%] Built target test_use_fd_ipc
[ 76%] Built target test_req_relaxed
[ 76%] Built target test_radio_dish
[ 76%] Built target test_conflate
[ 77%] Built target test_immediate
[ 78%] Built target test_term_endpoint
[ 79%] Built target test_reqrep_tcp
[ 80%] Built target test_pair_inproc
[ 80%] Built target test_last_endpoint
[ 80%] Built target test_stream_disconnect
[ 80%] Built target test_sodium
[ 80%] Built target test_msg_flags
[ 81%] Built target test_ctx_options
[ 82%] Built target test_reqrep_inproc
[ 83%] Built target test_msg_ffn
[ 84%] Built target test_invalid_rep
[ 85%] Built target test_spec_router
[ 85%] Built target test_hwm
[ 85%] Built target test_router_mandatory
[ 85%] Built target test_inproc_connect
[ 85%] Built target test_hwm_pubsub
[ 85%] Built target test_reqrep_ipc
[ 87%] Built target test_sub_forward
[ 87%] Built target test_disconnect_inproc
[ 88%] Built target test_setsockopt
[ 88%] Built target test_connect_resolve
[ 88%] Built target test_iov
[ 89%] Built target test_req_correlate
[ 89%] Built target test_reqrep_device
[ 89%] Built target test_spec_rep
[ 90%] Built target test_unbind_inproc
[ 90%] Built target test_proxy_single_socket
[ 90%] Built target test_ctx_destroy
[ 91%] Built target test_security_curve
[ 91%] Built target test_unbind_wildcard
[ 91%] Built target test_diffserv
[ 92%] Built target test_fork
[ 92%] Built target test_probe_router
[ 93%] Built target test_zmq_poll_fd
[ 94%] Built target test_spec_req
[ 94%] Built target test_shutdown_stress
[ 94%] Built target test_proxy_terminate
[ 94%] Built target test_spec_dealer
[ 94%] Built target test_scatter_gather
[ 95%] Built target test_stream
[ 96%] Built target test_spec_pushpull
[ 97%] Built target test_many_sockets
[ 98%] Built target test_client_server
[ 98%] Built target test_system
[ 99%] Built target test_issue_566
[ 99%] Built target test_timeo
[ 99%] Built target test_security_null
[100%] Built target test_connect_rid
Install the project...
-- Install configuration: "Release"
-- Installing: /tmp/test/lib/pkgconfig/libzmq.pc
-- Installing: /tmp/test/bin/local_lat
-- Set runtime path of "/tmp/test/bin/local_lat" to ""
-- Installing: /tmp/test/bin/remote_lat
-- Set runtime path of "/tmp/test/bin/remote_lat" to ""
-- Installing: /tmp/test/bin/local_thr
-- Set runtime path of "/tmp/test/bin/local_thr" to ""
-- Installing: /tmp/test/bin/remote_thr
-- Set runtime path of "/tmp/test/bin/remote_thr" to ""
-- Installing: /tmp/test/bin/inproc_lat
-- Set runtime path of "/tmp/test/bin/inproc_lat" to ""
-- Installing: /tmp/test/bin/inproc_thr
-- Set runtime path of "/tmp/test/bin/inproc_thr" to ""
-- Installing: /tmp/test/lib/libzmq.so.4.2.3
-- Installing: /tmp/test/lib/libzmq.so.5.1.3
-- Installing: /tmp/test/lib/libzmq.so
-- Installing: /tmp/test/include/zmq.h
-- Installing: /tmp/test/include/zmq_utils.h
-- Installing: /tmp/test/lib/libzmq.a
-- Up-to-date: /tmp/test/include/zmq.h
-- Up-to-date: /tmp/test/include/zmq_utils.h
-- Installing: /tmp/test/share/zmq/AUTHORS.txt
-- Installing: /tmp/test/share/zmq/COPYING.txt
-- Installing: /tmp/test/share/zmq/COPYING.LESSER.txt
-- Installing: /tmp/test/share/zmq/NEWS.txt
-- Installing: /tmp/test/doc/zmq/zmq.html
-- Installing: /tmp/test/doc/zmq/zmq_atomic_counter_dec.html
-- Installing: /tmp/test/doc/zmq/zmq_atomic_counter_destroy.html
-- Installing: /tmp/test/doc/zmq/zmq_atomic_counter_inc.html
-- Installing: /tmp/test/doc/zmq/zmq_atomic_counter_new.html
-- Installing: /tmp/test/doc/zmq/zmq_atomic_counter_set.html
-- Installing: /tmp/test/doc/zmq/zmq_atomic_counter_value.html
-- Installing: /tmp/test/doc/zmq/zmq_bind.html
-- Installing: /tmp/test/doc/zmq/zmq_close.html
-- Installing: /tmp/test/doc/zmq/zmq_connect.html
-- Installing: /tmp/test/doc/zmq/zmq_ctx_destroy.html
-- Installing: /tmp/test/doc/zmq/zmq_ctx_get.html
-- Installing: /tmp/test/doc/zmq/zmq_ctx_new.html
-- Installing: /tmp/test/doc/zmq/zmq_ctx_set.html
-- Installing: /tmp/test/doc/zmq/zmq_ctx_shutdown.html
-- Installing: /tmp/test/doc/zmq/zmq_ctx_term.html
-- Installing: /tmp/test/doc/zmq/zmq_curve.html
-- Installing: /tmp/test/doc/zmq/zmq_curve_keypair.html
-- Installing: /tmp/test/doc/zmq/zmq_curve_public.html
-- Installing: /tmp/test/doc/zmq/zmq_disconnect.html
-- Installing: /tmp/test/doc/zmq/zmq_errno.html
-- Installing: /tmp/test/doc/zmq/zmq_getsockopt.html
-- Installing: /tmp/test/doc/zmq/zmq_gssapi.html
-- Installing: /tmp/test/doc/zmq/zmq_has.html
-- Installing: /tmp/test/doc/zmq/zmq_init.html
-- Installing: /tmp/test/doc/zmq/zmq_inproc.html
-- Installing: /tmp/test/doc/zmq/zmq_ipc.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_close.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_copy.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_data.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_get.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_gets.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_init.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_init_data.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_init_size.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_more.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_move.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_recv.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_routing_id.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_send.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_set.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_set_routing_id.html
-- Installing: /tmp/test/doc/zmq/zmq_msg_size.html
-- Installing: /tmp/test/doc/zmq/zmq_null.html
-- Installing: /tmp/test/doc/zmq/zmq_pgm.html
-- Installing: /tmp/test/doc/zmq/zmq_plain.html
-- Installing: /tmp/test/doc/zmq/zmq_poll.html
-- Installing: /tmp/test/doc/zmq/zmq_proxy.html
-- Installing: /tmp/test/doc/zmq/zmq_proxy_steerable.html
-- Installing: /tmp/test/doc/zmq/zmq_recv.html
-- Installing: /tmp/test/doc/zmq/zmq_recvmsg.html
-- Installing: /tmp/test/doc/zmq/zmq_send.html
-- Installing: /tmp/test/doc/zmq/zmq_send_const.html
-- Installing: /tmp/test/doc/zmq/zmq_sendmsg.html
-- Installing: /tmp/test/doc/zmq/zmq_setsockopt.html
-- Installing: /tmp/test/doc/zmq/zmq_socket.html
-- Installing: /tmp/test/doc/zmq/zmq_socket_monitor.html
-- Installing: /tmp/test/doc/zmq/zmq_strerror.html
-- Installing: /tmp/test/doc/zmq/zmq_tcp.html
-- Installing: /tmp/test/doc/zmq/zmq_term.html
-- Installing: /tmp/test/doc/zmq/zmq_tipc.html
-- Installing: /tmp/test/doc/zmq/zmq_udp.html
-- Installing: /tmp/test/doc/zmq/zmq_unbind.html
-- Installing: /tmp/test/doc/zmq/zmq_version.html
-- Installing: /tmp/test/doc/zmq/zmq_vmci.html
-- Installing: /tmp/test/doc/zmq/zmq_z85_decode.html
-- Installing: /tmp/test/doc/zmq/zmq_z85_encode.html
-- Installing: /tmp/test/share/cmake/ZeroMQ/ZeroMQTargets.cmake
-- Installing: /tmp/test/share/cmake/ZeroMQ/ZeroMQTargets-release.cmake
-- Installing: /tmp/test/share/cmake/ZeroMQ/ZeroMQConfig.cmake
-- Installing: /tmp/test/share/cmake/ZeroMQ/ZeroMQConfigVersion.cmake
```

and

```
$ cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/test
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cppzmq v4.2.3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/luca/git/cppzmq/build
$ make install
Install the project...
-- Install configuration: ""
-- Up-to-date: /tmp/test/include/zmq.hpp
-- Up-to-date: /tmp/test/include/zmq_addon.hpp
-- Installing: /tmp/test/share/cmake/cppzmq/cppzmqTargets.cmake
-- Installing: /tmp/test/share/cmake/cppzmq/cppzmqConfig.cmake
-- Installing: /tmp/test/share/cmake/cppzmq/cppzmqConfigVersion.cmake
```

**Comment by stevemk14ebr** [comment]
Ok i don't know what the issue was but it appears to work when i follow your commands exactly. If i submit a PR with build instruction will it be merged, the only docs in libzmq are for the autoconf build, and this repo has no instructions at all. I'd like to document them.

**Comment by bluca** [comment]
Sure, thanks

**Pull request closed without merging**
