### PR TITLE
Problem: cpp-coveralls can no longer be installed using Python2 pip.

### PR DESCRIPTION
**Pull request by sigiesec**
Solution: Use pip3 instead of pip to install coveralls.

### CODE REVIEW

**Comment by sigiesec** [comment]
@bluca Not sure if you are watching cppzmq, could you merge this?

**Comment by bluca** [comment]
Sorry, not actively watching this repo

**Comment by sigiesec** [comment]
That's what I was thinking :) Never mind.

Just wondering, what about giving @gummif permissions for the repo as well? They have made a lot of contributions over the past months, and while I try to keep up I don't have so much time to keep a close eye on this right now.

**Comment by sigiesec** [comment]
Or rather years than months that is

**Comment by bluca** [comment]
Sure - @gummif does that work for you? Do you have 2FA active on your account?

**Comment by gummif** [comment]
Yes that's fine. I have 2FA.

**Comment by bluca** [comment]
great - sent you an invite

**Comment by gummif** [comment]
I can't see any invite in my notifications...

**Comment by bluca** [comment]
Welcome to the team!

**Comment by gummif** [comment]
Thanks 👍

**Pull request merged**
